### ISSUE TITLE
Some bars are missing for some plots

### ISSUE THREAD

**Issue by hpages** [Bioconductor/bio-web-stats#12]
No bars for values <= 10.

See for example the plot for year 2022 for **BSgenome.Hsapiens.UCSC.hg17** at http://stats.test.bioconductor.org/packages/stats/data-annotation/BSgenome.Hsapiens.UCSC.hg17/

No bars for Aug, and only one bar for Feb!

The choice to plot only values > 10 seems to be hardcoded. Maybe use a min y of 1 instead? That won't totally solve the problem (values of 1 won't get plotted) but maybe that's ok.

Thanks

**Comment by rdshear** [comment]
We can plot 1 as well by making the minimum 0.1. Sorry. I took the liberty because so much real estate was being used by low orders of magnitude. But I broke my own design rule of matching the formats, so I will change the scale.

**Comment by rdshear** [comment]
Changed the minimum to 0.9. `dc466a6`
