### ISSUE TITLE
Reported BioC version where a package was "last seen" is one version behind real version

### ISSUE THREAD

**Issue by hpages** [Bioconductor/bio-web-stats#15]
E.g. according to the stats **bigPint** was last seen in BioC 3.17: https://bioconductor.org/packages/stats/bioc/bigPint

However the package was still part of BioC 3.18 (that's when it got deprecated):
- https://bioconductor.org/packages/3.18/bigPint

Then it got removed from BioC 3.19:
- https://bioconductor.org/packages/3.19/bigPint

Same problem with other "old" packages e.g. **epihet**: last seen in 3.16 according to https://bioconductor.org/packages/stats/bioc/epihet/
but was actually last seen in 3.17:
- https://bioconductor.org/packages/3.17/epihet/
- https://bioconductor.org/packages/3.18/epihet/

**Comment by rdshear** [comment]
This seems to be a consequence of #16. I will address them simultaneously.

**Comment by hpages** [comment]
any chance this can be fixed @rdshear ? Thx

**Comment by hpages** [comment]
The problem remains. Can we reopen until the problem gets addressed?
