### ISSUE TITLE
Package download page: Home page link for deprecated packages

### ISSUE THREAD

**Issue by rdshear** [Bioconductor/bio-web-stats#2]
The normal home page link on the package downloads page yields 404 when the package is depricated.
Example:
cosmo home page: [release version](https://bioconductor.org/packages/release/bioc/html/cosmo.html), [devel version](https://bioconductor.org/packages/devel/bioc/html/cosmo.html).

It should warn that the package is deprecated and point to the last available version.

**Comment by rdshear** [comment]
When the old system identified a deprecated package, it replaced links to the package home pages with the message 
```
Note that **PACKAGENAME** doesn't belong to the current release or devel version of Bioconductor anymore.
```

**Comment by hpages** [comment]
It actually depends:
- If the package is still present in the current release and devel versions, the 2 links are displayed, like here: https://bioconductor.org/packages/stats/bioc/BiocVersion/
- If the package is only present in one of the two, only one link is displayed, like here: https://bioconductor.org/packages/stats/bioc/betaHMM/
- If the package is no longer present in release or devel, then the above message is displayed, like here: https://bioconductor.org/packages/stats/bioc/BiocInstaller/

The algo is very straightforward: all it does is check for the validity of the link to the package landing pages in release and devel. In particular there's no attempt to track the history of the package e.g. when it was added or removed to/from BioC etc...
