### ISSUE TITLE
visual table doesn't match .tab file

### ISSUE THREAD

**Issue by rdshear** [Bioconductor/bio-web-stats#6]
xyz.tab doesn't match table in /packages/software/xyz/

**Comment by lshep** [comment]
Claim that the tab links reported same stats for all packages:  https://community-bioc.slack.com/archives/C35G93GJH/p1704170896589869
Claim that front table stats not matching tab stats:  https://community-bioc.slack.com/archives/C35G93GJH/p1704191849720879

**Comment by rdshear** [comment]
These both look correct now. May have resolved as a result of the revision of the database schema.
