### ISSUE TITLE
docker-compose failure?

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/bio-web-stats#8]
attempting to follow README with `docker-compose up flask-prod` after
`git clone https://github.com/Bioconductor/bio-web-stats.git`, at `commit 54dba3e`
```
ERROR: failed to solve: python:3.12-slim-buster: docker.io/library/python:3.12-slim-buster: not found
ERROR: Service 'flask-prod' failed to build : Build failed
```

**Comment by rdshear** [comment]
We used [cookiecutter-flask](https://github.com/cookiecutter-flask/cookiecutter-flask/) to generate the skeleton for this application. During this period of rapid development we have not kept the README.md up to date. We will add an appropriate caution to the existing README.md and revise or rewrite it as necessary while wrapping up.

**Comment by rdshear** [comment]
Will be dealt with as part of general project closeout.
